name: Daily Weather Update

on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run daily update
        env:
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
        run: python daily_update.py
      - name: Upload dataset artifact
        uses: actions/upload-artifact@v4  # Or v3 if v4 isn’t out yet
        with:
          name: dataset
          path: data/mandi_weather_data_preprocessed.csv
          retention-days: 1
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model/xgb_model_*.pkl
          retention-days: 1
